name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions

env:
  GITHUB_ACTIONS: true

on:
  pull_request:
    branches: [ "main" ]

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Show GITHUB_ACTIONS env variable
      run: echo ${{ env.GITHUB_ACTIONS }}
    - name: Show name of branch and repository
      run: echo "Branch - ${{ github.head_ref }}, Repository - ${{ github.repository }}"
    - name: Show event name that triggered workflow
      run: echo "Event - ${{ github.event_name }}"
